#ifndef APPLICATIONLIB_GLOBAL_H
#define APPLICATIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPLICATIONLIB_LIBRARY)
#  define APPLICATIONLIB_EXPORT Q_DECL_EXPORT
#else
#  define APPLICATIONLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATIONLIB_GLOBAL_H
